
name: First Interaction

on:
  pull_request:
    branches: [ master ]
  issue_comment: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Welcome to the BracketJS repository! Please make a descriptive bug report!'
          pr-message: 'Thanks for your contributions, make sure to include feat: or fix: at the beginning of your PR name!'
