name: Minify
on:
  workflow_dispatch:
  push:
   branches:
     - master

jobs:
  add-contributors:
    runs-on: ubuntu-latest
    steps:
      - uses: nizarmah/auto-minify@v2.1.1
        with:
          directory: .
          overwrite: true
          
