name: Minify
on:
  workflow_dispatch:
  push:
   branches:
     - master

jobs:
  minify:
    name: Minify
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
     - uses: nizarmah/auto-minify@v2.1.1
       with:
          directory: .
          overwrite: true
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMIT_MESSAGE: "Minify"
    
