
name: CI

on:
  schedule:
    - cron: "* * * * *"
  workflow_dispatch:

jobs:
  action:
    runs-on: ubuntu-latest

    steps:
      - name: Close Stale Issues
      - uses: actions/stale@v5.0.0
        with:
          stale-issue-message: "Your issue report has not had any activity for 30 days! Make a post or the issue will be closed!"
          close-pr-message: "Closing PR!"
          close-issue-message: "Closing Issue"
          stale-pr-message: "Your pr has not had any activity for 30 days! Push a commit or it will be closed!"
          days-before-stale: 30
